@url = http://localhost:3000/v1
@devurl = http://api.oneteam.tech/v1


###

GET {{devurl}}/user/viewUserRatings

###

GET {{url}}/user/viewUserRatings

###

GET https://app.asana.com/api/1.0/tasks/1202114431843813
Authorization: Bearer 1/4670926474297:eaced3c8e74f1fac6a9ae3665086a0d6